// Async Request
export const SEARCH_COURTS_REQUEST = 'SEARCH_COURTS_REQUEST';
export const SEARCH_COURTS_SUCCESS = 'SEARCH_COURTS_SUCCESS';
export const SEARCH_COURTS_FAILURE = 'SEARCH_COURTS_FAILURE';

export const SEARCH_COURT_REQUEST = 'SEARCH_COURT_REQUEST';
export const SEARCH_COURT_SUCCESS = 'SEARCH_COURT_SUCCESS';
export const SEARCH_COURT_FAILURE = 'SEARCH_COURT_FAILURE';

export const LOG_IN_REQUEST = 'LOG_IN_REQUEST';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';

export const LOG_OUT_REQUEST = 'LOG_OUT_REQUEST';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';
export const LOG_OUT_FAILURE = 'LOG_OUT_FAILURE';

// Court Info Reducer
export const ADD_COURTS = 'ADD_COURTS';
export const DELETE_COURTS = 'DELETE_SEARCHED_COURTS';
export const SELECT_COURT = 'SELECT_COURT';
export const UNSELECT_COURT = 'UNSELECT_COURT';
export const REMOVE_SELECT_COURT = 'REMOVE_SELECT_COURT';
export const MOUSEOVER_LIST = 'MOUSEOVER_LIST';

// UI Controlling Reducer
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const OPEN_NICKNAME_CHANGER = 'OPEN_NICKNAME_CHANGER';
export const CLOSE_NICKNAME_CHANGER = 'CLOSE_NICKNAME_CHANGER';
export const TOGGLE_USER_MENU = 'TOGGLE_USER_MENU';
export const NO_DATA = '정보없음';

// Filter Info Reducer
export const GET_FILTER_INPUT = 'GET_FILTER_INPUT';
export const GET_SEARCH_INPUT = 'GET_SEARCH_INPUT';
export const INIT_FILTER_INPUT = 'INIT_FILTER_INPUT';