// Court Info Reducer
// Async Request
export const SEARCH_COURTS_REQUEST = 'SEARCH_COURTS_REQUEST';
export const SEARCH_COURTS_SUCCESS = 'SEARCH_COURTS_SUCCESS';
export const SEARCH_COURTS_FAILURE = 'SEARCH_COURTS_FAILURE';

export const ADD_COURTS = 'ADD_COURTS';
export const DELETE_COURTS = 'DELETE_SEARCHED_COURTS';
export const SELECT_COURT = 'SELECT_COURT';
export const REMOVE_SELECT_COURT = 'REMOVE_SELECT_COURT';
export const LIST_OVER_COURT = 'LIST_OVER_COURT';
export const LIST_OUT_COURT = 'LIST_OUT_COURT';
export const USER_INPUT = 'USER_INPUT';

// UI Controlling Reducer
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const OPEN_COURTADDITION = 'OPEN_COURTADDITION';
export const CLOSE_COURTADDITION = 'CLOSE_COURTADDITION';
export const TOGGLE_FILTER = 'TOGGLE_FILTER';
export const NO_DATA = '정보없음';

// Filter Info Reducer
export const ACTIVE_BUTTON = 'ACTIVE_BUTTON';
export const SEND_FILTER_DATA = 'SEND_FILTER_DATA';
export const INIT_FILTER_DATA = 'INIT_FILTER_DATA';