// Async Request
export const SEARCH_COURTS_REQUEST = 'SEARCH_COURTS_REQUEST';
export const SEARCH_COURTS_SUCCESS = 'SEARCH_COURTS_SUCCESS';
export const SEARCH_COURTS_FAILURE = 'SEARCH_COURTS_FAILURE';

// Court Info Reducer
export const ADD_COURTS = 'ADD_COURTS';
export const DELETE_COURTS = 'DELETE_SEARCHED_COURTS';
export const SELECT_COURT = 'SELECT_COURT';
export const UNSELECT_COURT = 'UNSELECT_COURT';
export const REMOVE_SELECT_COURT = 'REMOVE_SELECT_COURT';
export const MOUSEOVER_LIST = 'MOUSEOVER_LIST';
export const USER_INPUT = 'USER_INPUT';

// UI Controlling Reducer
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const OPEN_COURTADDITION = 'OPEN_COURTADDITION';
export const CLOSE_COURTADDITION = 'CLOSE_COURTADDITION';
export const NO_DATA = '정보없음';

// Filter Info Reducer
export const SEND_FILTER_INPUT = 'SEND_FILTER_INPUT';
export const INIT_FILTER_INPUT = 'INIT_FILTER_INPUT';